
from bson import ObjectId

class ManagerCRUD:
    """
    A generic CRUD manager for handling a list of dictionaries stored in a JSON file.
    Each item in the list is expected to be a dictionary with a unique 'id' field.
    """

    def __init__(self, collection):
        self.collection = collection

    def _load_data(self):
        """Load data from Mongo file. Everything by far"""
        return list(self.collection.find())

    def create(self, entry):
        """
        Create a new item to the mongo collection, 
        I dont need to check for id because mongo will auto generate one for me,
         and I can use that as the unique identifier
        """
        self.collection.insert_one(entry)
        return entry

    def read_all(self):
        """Read all items. returns a list. including the _id field generated by mongo
            return a dictionary with the _id field converted to string for easier handling in the front-end
        """
        items = self._load_data()

        # Convert _id to string for all
        for entry in items:
            entry["_id"] = str(entry["_id"])
        return items
    
    def read_without_id(self):
        """Read all items. returns a list. excluding the _id field generated by mongo
            this is useful for the front-end when we dont want to expose the _id field to the user
        """
        
        return list(self.collection.find({}, {"_id": 0}))

    def read_by_id(self, item_id):
        """Read a single item by id."""
        data = self._load_data()
        for item in data:
            if str(item.get("_id")) == str(item_id):
                return item
        return None


    
    def update(self, item_id, updated_item):

        """ Udpates an item and store it back to the mongo collection
            It will return the True item was successfully updated, or False if the item was not found.
        """
        result = self.collection.update_one(
            {"_id": ObjectId(item_id)},
            {"$set": updated_item}
        )
        return result.modified_count > 0

    def delete(self, item_id):
        """Delete an item by id."""
        result = self.collection.delete_one({"_id": ObjectId(item_id)})
        return result.deleted_count > 0